# Generated by Django 4.1 on 2022-08-30 13:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(blank=True, default='', max_length=10)),
                ('traducao', models.CharField(blank=True, default='', max_length=20)),
            ],
            options={
                'verbose_name': 'Area',
                'verbose_name_plural': 'Areas',
                'db_table': 'area',
            },
        ),
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(choices=[('A', 'A'), ('D', 'D'), ('E', 'E'), ('F', 'F'), ('M', 'M'), ('O', 'O'), ('P', 'P'), ('T', 'T')], max_length=20)),
                ('traducao', models.CharField(blank=True, default='', max_length=20)),
            ],
            options={
                'verbose_name': 'Departamento',
                'verbose_name_plural': 'Departamentos',
                'db_table': 'departamentos',
            },
        ),
        migrations.CreateModel(
            name='Linha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(blank=True, default='', max_length=10)),
                ('traducao', models.CharField(blank=True, default='', max_length=20)),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='linhas', to='equipamentos.area')),
            ],
            options={
                'verbose_name': 'Linha',
                'verbose_name_plural': 'Linhas',
                'db_table': 'linhas',
            },
        ),
        migrations.CreateModel(
            name='Planta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(choices=[('CMO1', 'CMO1'), ('VP01', 'VP01'), ('VU01', 'VU01')], max_length=4, unique=True)),
                ('traducao', models.CharField(blank=True, default='', max_length=20)),
            ],
            options={
                'verbose_name': 'Planta',
                'verbose_name_plural': 'Plantas',
                'db_table': 'plantas',
            },
        ),
        migrations.CreateModel(
            name='Zona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(blank=True, default='', max_length=10)),
                ('traducao', models.CharField(blank=True, default='', max_length=20)),
                ('linha', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='equipamentos.linha')),
            ],
            options={
                'verbose_name': 'Zona',
                'verbose_name_plural': 'Zonas',
                'db_table': 'zonas',
            },
        ),
        migrations.CreateModel(
            name='Posto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(blank=True, default='', max_length=10)),
                ('traducao', models.CharField(blank=True, default='', max_length=20)),
                ('zona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='equipamentos.zona')),
            ],
            options={
                'verbose_name': 'Posto',
                'verbose_name_plural': 'Postos',
                'db_table': 'postos',
            },
        ),
        migrations.CreateModel(
            name='Equipamento',
            fields=[
                ('codigo_sap', models.IntegerField(primary_key=True, serialize=False, verbose_name='Código SAP')),
                ('denominacao', models.CharField(blank=True, max_length=250)),
                ('denominacao_linha', models.CharField(blank=True, max_length=250)),
                ('local', models.CharField(blank=True, max_length=50)),
                ('sala', models.CharField(blank=True, max_length=50)),
                ('codigo_abc', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('A', 'A'), ('B', 'B'), ('C', 'C')], max_length=4)),
                ('qrcode', models.CharField(blank=True, max_length=255)),
                ('data_criacao', models.CharField(blank=True, max_length=50)),
                ('data_edicao', models.CharField(blank=True, max_length=50)),
                ('criado_por', models.CharField(blank=True, max_length=50)),
                ('editado_por', models.CharField(blank=True, max_length=50)),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipamentos', to='equipamentos.area')),
                ('departamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipamentos', to='equipamentos.departamento')),
                ('equip_superior', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='filho', to='equipamentos.equipamento')),
                ('linha', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipamentos', to='equipamentos.linha')),
                ('planta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipamentos', to='equipamentos.planta')),
                ('posto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipamentos', to='equipamentos.posto')),
                ('zona', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='equipamentos', to='equipamentos.zona')),
            ],
            options={
                'verbose_name': 'Equipamento',
                'verbose_name_plural': 'Equipamentos',
                'db_table': 'equipamentos',
            },
        ),
        migrations.AddField(
            model_name='departamento',
            name='planta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departamentos', to='equipamentos.planta'),
        ),
        migrations.AddField(
            model_name='area',
            name='departamento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='areas', to='equipamentos.departamento'),
        ),
    ]
