# Generated by Django 4.1 on 2022-08-31 11:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('equipamentos', '0002_alter_equipamento_area_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipamento',
            name='observacoes',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='equipamento',
            name='planta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='equipamentos', to='equipamentos.planta'),
        ),
    ]
