# Generated by Django 4.1 on 2023-06-21 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestao_competencia_teste', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='membro',
            old_name='id',
            new_name='ID',
        ),
        migrations.RenameField(
            model_name='membro',
            old_name='id_cargo',
            new_name='cargo',
        ),
        migrations.RenameField(
            model_name='membro',
            old_name='id_setor',
            new_name='setor',
        ),
    ]
