# Generated by Django 4.1 on 2023-06-22 09:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestao_competencia_teste', '0002_rename_id_membro_id_rename_id_cargo_membro_cargo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tecnologia',
            fields=[
                ('nome', models.CharField(max_length=255, primary_key=True, serialize=False)),
            ],
            options={
                'verbose_name': 'Tecnologia',
                'verbose_name_plural': 'Tecnologias',
                'db_table': 'c_tecnologia',
            },
        ),
        migrations.AlterModelOptions(
            name='cargo',
            options={'verbose_name': 'Cargo', 'verbose_name_plural': 'Cargos'},
        ),
        migrations.AlterModelOptions(
            name='membro',
            options={'verbose_name': 'Membro', 'verbose_name_plural': 'Membros'},
        ),
        migrations.AlterModelOptions(
            name='setor',
            options={'verbose_name': 'Setor', 'verbose_name_plural': 'Setores'},
        ),
        migrations.AlterField(
            model_name='cargo',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='membro',
            name='cargo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestao_competencia_teste.cargo'),
        ),
        migrations.AlterField(
            model_name='membro',
            name='setor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestao_competencia_teste.setor'),
        ),
        migrations.AlterField(
            model_name='setor',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.CreateModel(
            name='Formacao',
            fields=[
                ('nome', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('descricao', models.CharField(max_length=255)),
                ('duracao', models.CharField(max_length=255)),
                ('id_tecnologia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestao_competencia_teste.tecnologia')),
            ],
            options={
                'verbose_name': 'Formacao',
                'verbose_name_plural': 'Formacoes',
                'db_table': 'c_formacoes',
            },
        ),
        migrations.CreateModel(
            name='Competencia',
            fields=[
                ('nome', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('id_setor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestao_competencia_teste.setor')),
                ('id_tecnologia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestao_competencia_teste.tecnologia')),
            ],
            options={
                'verbose_name': 'Competencia',
                'verbose_name_plural': 'Competencias',
                'db_table': 'c_competencias',
            },
        ),
    ]
