# Generated by Django 4.1 on 2023-06-22 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestao_competencia_teste', '0005_rename_id_setor_competencia_setor_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='setor',
            options={'verbose_name': 'Setor', 'verbose_name_plural': 'Setors'},
        ),
        migrations.AddField(
            model_name='cargo',
            name='classe',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='membro',
            name='pesquisa',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
