version: "3"

services:
  web:
    container_name: web
    build: .
    restart: always
    environment:
    - POSTGRES_DB=platec
    - POSTGRES_USER=platec
    - POSTGRES_PASSWORD=platec
    ports: 
      - "8000:8000"
      - "8501:8501"
    volumes:
      - .:/app/

  db:
    container_name: db
    image: postgres
    environment:
    - POSTGRES_DB=platec
    - POSTGRES_USER=platec
    - POSTGRES_PASSWORD=platec
    restart: always
    volumes:
      - bancodedadospg:/var/lib/postgresql/data
    ports:
      - 5432:5432

volumes:
  bancodedadospg:
    external: true