# Generated by Django 4.1 on 2023-06-22 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestao_competencia', '0003_tecnologia_alter_cargo_options_alter_membro_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='membro',
            old_name='ID',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='membro',
            old_name='cargo',
            new_name='id_cargo',
        ),
        migrations.RenameField(
            model_name='membro',
            old_name='setor',
            new_name='setor_id',
        ),
    ]
