# Generated by Django 4.1 on 2022-08-30 13:25

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('equipamentos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OcorrenciaPlatec',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sintoma', models.TextField(verbose_name='Sintoma')),
                ('causa', models.TextField(blank=True, null=True, verbose_name='Causa')),
                ('remedio', models.TextField(blank=True, null=True, verbose_name='Remédio')),
                ('categoria', models.CharField(choices=[('Automação', 'Automação'), ('Eletrônico', 'Eletrônico'), ('Eletrica', 'Eletrica'), ('Hidráulica', 'Hidráulica'), ('Informática', 'Informática'), ('Mecanica', 'Mecanica'), ('Robô', 'Robô'), ('Outro', 'Outro')], max_length=25, verbose_name='Categoria')),
                ('turno', models.CharField(choices=[('1 Turno', '1° Turno'), ('2 Turno', '2° Turno')], max_length=25, verbose_name='Turno')),
                ('horario_quebra', models.DateTimeField(blank=True, default=django.utils.timezone.now, help_text='Horario da quebra', null=True, verbose_name='Hora Pane')),
                ('horario_chamado', models.DateTimeField(blank=True, default=django.utils.timezone.now, help_text='Hora que a Platec foi acionada', null=True, verbose_name='Hora Platec')),
                ('tempo_eqp_parado', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Tempo parado')),
                ('veiculos_perdidos', models.PositiveIntegerField(blank=True, help_text='Veiculos perdido', null=True, verbose_name='Percas')),
                ('marcha_degradada', models.CharField(blank=True, help_text='Se houve marcha degradada, descreva', max_length=100, null=True, verbose_name='Marcha degradada')),
                ('mbr', models.PositiveIntegerField(blank=True, null=True, verbose_name='MBR')),
                ('equipamento', models.ForeignKey(help_text='ID equipamento SAP', on_delete=django.db.models.deletion.CASCADE, related_name='ocorrencias', to='equipamentos.equipamento', verbose_name='Código SAP Equipamento')),
            ],
            options={
                'verbose_name': 'Quebra de equipamento',
                'verbose_name_plural': 'Quebra de equipamentos',
                'db_table': 'quebra_equipamentos',
                'ordering': ['-horario_quebra'],
            },
        ),
    ]
