# Generated by Django 4.1 on 2022-09-05 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ocorrencias', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ocorrenciaplatec',
            name='veiculos_perdidos',
            field=models.PositiveIntegerField(blank=True, help_text='Veiculos perdido', null=True, verbose_name='Perdas'),
        ),
    ]
