# Generated by Django 4.1 on 2023-03-30 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ocorrencias', '0002_alter_ocorrenciaplatec_veiculos_perdidos'),
    ]

    operations = [
        migrations.AddField(
            model_name='ocorrenciaplatec',
            name='perdas_rgu',
            field=models.PositiveBigIntegerField(blank=True, null=True, verbose_name='Perdas RGU'),
        ),
    ]
