# Generated by Django 4.1 on 2024-04-05 16:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cargo',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=255)),
                ('classe', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Cargo',
                'verbose_name_plural': 'Cargos',
                'db_table': 'c_cargo',
            },
        ),
        migrations.CreateModel(
            name='Competencia',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Competencia',
                'verbose_name_plural': 'Competencias',
                'db_table': 'c_competencias',
            },
        ),
        migrations.CreateModel(
            name='Formacao',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=255)),
                ('descricao', models.CharField(max_length=255)),
                ('duracao', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Formacao',
                'verbose_name_plural': 'Formacoes',
                'db_table': 'c_formacoes',
            },
        ),
        migrations.CreateModel(
            name='FormacaoPrevista',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('formador', models.CharField(max_length=255)),
                ('vagas', models.CharField(max_length=255)),
                ('duracao', models.CharField(max_length=255)),
                ('local', models.CharField(max_length=255)),
                ('datainicial', models.DateField()),
                ('datafinal', models.DateField()),
                ('vagasdisponiveis', models.CharField(max_length=255)),
                ('Elearning', models.CharField(max_length=255)),
                ('status', models.CharField(max_length=255)),
                ('formacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='c_formacos_previstas', to='gestao_competencia_servidor.formacao')),
            ],
            options={
                'verbose_name': 'Formacao Prevista',
                'verbose_name_plural': 'Formacao Previstas',
                'db_table': 'c_formacoes_previstas',
            },
        ),
        migrations.CreateModel(
            name='Membro',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('supervisor', models.CharField(max_length=255)),
                ('area', models.CharField(max_length=255)),
                ('cargo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='c_membro', to='gestao_competencia_servidor.cargo')),
            ],
            options={
                'verbose_name': 'Membro',
                'verbose_name_plural': 'Membros',
                'db_table': 'c_membro',
            },
        ),
        migrations.CreateModel(
            name='Setor',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Setor',
                'verbose_name_plural': 'Setors',
                'db_table': 'c_setor',
            },
        ),

        migrations.CreateModel(
            name='Tecnologia',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Tecnologia',
                'verbose_name_plural': 'Tecnologias',
                'db_table': 'c_tecnologia',
            },
        ),
        migrations.CreateModel(
            name='MembroFormacao',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('formacao_prevista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='c_formacaoid_membroid', to='gestao_competencia_servidor.formacaoprevista')),
                ('membro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='c_formacaoid_membroid', to='gestao_competencia_servidor.membro')),
            ],
            options={
                'verbose_name': 'Membro Formacao',
                'verbose_name_plural': 'Membro Formacoes',
                'db_table': 'c_formacaoid_membroid',
            },
        ),
        migrations.AddField(
            model_name='membro',
            name='setor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='c_membro', to='gestao_competencia_servidor.setor'),
        ),
        migrations.CreateModel(
            name='Matriz',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('area', models.CharField(max_length=255)),
                ('nivel_percentual', models.DecimalField(decimal_places=2, max_digits=5)),
                ('competencias', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestao_competencia_servidor.competencia')),
                ('setor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestao_competencia_servidor.setor')),
            ],
            options={
                'db_table': 'c_areas_competencias',
            },
        ),
        migrations.CreateModel(
            name='FormacaoCompetencia',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('competencias', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='c_formacoes_competencias', to='gestao_competencia_servidor.competencia')),
                ('formacoes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='c_formacoes_competencias', to='gestao_competencia_servidor.formacao')),
            ],
        ),
        migrations.AddField(
            model_name='formacao',
            name='tecnologia',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='c_formacoes', to='gestao_competencia_servidor.tecnologia'),
        ),
        migrations.CreateModel(
            name='ConsultaFormacao',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Data', models.DateField(max_length=255)),
                ('formacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='c_membro_formacoes', to='gestao_competencia_servidor.formacao')),
                ('membro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='c_membro_formacoes', to='gestao_competencia_servidor.membro')),
            ],
            options={
                'verbose_name': 'Consulta Formacao',
                'verbose_name_plural': 'Consulta Formacoes',
                'db_table': 'c_membro_formacoes',
            },
        ),
        migrations.AddField(
            model_name='competencia',
            name='setor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='c_competencias', to='gestao_competencia_servidor.setor'),
        ),
        migrations.AddField(
            model_name='competencia',
            name='tecnologia',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='c_competencias', to='gestao_competencia_servidor.tecnologia'),
        ),
        migrations.CreateModel(
            name='ConsultaCompetencia',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nivel', models.CharField(default='0', max_length=255)),
                ('competencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='c_membro_competencias', to='gestao_competencia_servidor.competencia')),
                ('membro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='c_membro_competencias', to='gestao_competencia_servidor.membro')),
                ('setor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='c_membro_competencias', to='gestao_competencia_servidor.setor')),
            ],
            options={
                'verbose_name': 'Consulta Competencia',
                'verbose_name_plural': 'Consulta Competencias',
                'db_table': 'c_membro_competencias',
                'unique_together': {('membro', 'competencia')},
            },
        ),
    ]
