# Generated by Django 4.1 on 2024-04-08 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestao_competencia_servidor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='supervisor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=254)),
            ],
            options={
                'verbose_name': 'supervisor',
                'verbose_name_plural': 'supervisores',
                'db_table': 'supervisor',
            },
        ),
    ]
